---
- name: "Install ntp service"
  hosts: all

  tasks:
    - name: "Ensure NTP(for time synchronization) is installed."
      yum: name=ntp state=present 
    - name: "Ensure NTP is running."
      service: name=ntpd state=started enabled=yes
