apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volume:
  - name: "kuard-data"
    hostPath: 
      path: "/var/lib/kuard"
  containers:
  - image: dowa/kuard:1
    name: kuard
    volumeMounts:
    - mountPath: "/data"
        name: "kuard-data"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
