---

- name: "Installation Apache"
  hosts: "front"
  gather_facts: no
  tasks:
    - name: "Installation du package apache"
      package:
        name: "apache2"
        state: present
    - name: "Démarrer et activer le service au démarrage"
      service:
        name: "apache2"
        state: started
        enabled: yes
