---
- name: "Apache installation using docker"
  hosts: webserver
  pre_tasks:
  - name: install docker python
    pip: name=docker-py
  tasks:
  - name: Create apache container
    docker_container:
      name: webapp
      image: httpd
      ports: "80:80"
