Vagrant.configure("2") do |config|
config.vm.define "vm1" do |vm1|
vm1.vm.box = "centos/7"
vm1.vm.hostname = 'vm1'
vm1.vm.box_url = "centos/7"
vm1.vm.network "public_network", bridge: "wlp3s0: Wi-Fi (AirPort)", auto_config: false
end
end
